POST localhost:8080/creditDetail/create
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5Mjc2NSwiZXhwIjoxNTg5MTkzOTY1fQ.T7Ocvwk0X7SSfyRfTRuxkqkvIfTqz-pnI3ffHJ2BkFY

{
  "money": 1000,
  "creditName": "EUR360"
}

###

GET localhost:8080/creditDetail/find
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5MDk4OCwiZXhwIjoxNTg5MTkyMTg4fQ.vftF4JPTegfKV_fDtgPE0gftf5TFIofrZyIHSJDf6LI
###

POST localhost:8080/creditDetail/repay
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5Mjc2NSwiZXhwIjoxNTg5MTkzOTY1fQ.T7Ocvwk0X7SSfyRfTRuxkqkvIfTqz-pnI3ffHJ2BkFY

{
  "money": 1200,
  "creditName": "EUR360"
}
###

GET localhost:8080/creditDetail/admin/findById/1
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5MDk4OCwiZXhwIjoxNTg5MTkyMTg4fQ.vftF4JPTegfKV_fDtgPE0gftf5TFIofrZyIHSJDf6LI
###

GET localhost:8080/creditDetail/admin/findAllByStatus/CLOSED
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5MjM2NywiZXhwIjoxNTg5MTkzNTY3fQ.qRwUZeYXyvIWShdLyIoTpD6GM67HPnu-pXmDO5cr4Q4
###

POST localhost:8080/creditDetail/admin/findAllBetweenDate
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5MjM2NywiZXhwIjoxNTg5MTkzNTY3fQ.qRwUZeYXyvIWShdLyIoTpD6GM67HPnu-pXmDO5cr4Q4

{
  "firstDate": "31-12-2018",
  "secondDate": "31-12-2025"
}
###

DELETE localhost:8080/creditDetail/admin/deleteAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5MjM2NywiZXhwIjoxNTg5MTkzNTY3fQ.qRwUZeYXyvIWShdLyIoTpD6GM67HPnu-pXmDO5cr4Q4
###

PUT localhost:8080/creditDetail/admin/refreshAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE5MjM2NywiZXhwIjoxNTg5MTkzNTY3fQ.qRwUZeYXyvIWShdLyIoTpD6GM67HPnu-pXmDO5cr4Q4
###