POST localhost:8080/credit/admin/create
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

{
  "name": "USD721",
  "currencyType": "USD",
  "period": 720,
  "rate": 9
}

###

GET localhost:8080/credit/findAllAvailable
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

###

GET localhost:8080/credit/admin/findAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

###

GET localhost:8080/credit/admin/findById/1
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

DELETE localhost:8080/deposit/admin/deleteById/1
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

###

DELETE localhost:8080/deposit/admin/deleteAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

###