POST localhost:8080/depositDetail/create
Content-Type: application/json
token: huxueis-1020096634

{
  "money": 100,
  "currencyType": "USD",
  "depositName": "BYN360"
}
###

GET localhost:8080/depositDetail/getAll/132
Content-Type: application/json
token: test
###

PUT localhost:8080/depositDetail/pickUp
Content-Type: application/json
token: test
###

GET localhost:8080/depositDetail/getAllByStatus/UNAVAILABLE
Content-Type: application/json
token: test
###

POST localhost:8080/depositDetail//getAll/filterByCreateDate
Content-Type: application/json
token: test

{
  "firstDate": "31-12-2018",
  "secondDate": "31-12-2025"
}
###

DELETE localhost:8080/depositDetail/deleteAll
Content-Type: application/json
token: test

###