POST localhost:8080/depositDetail/create
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

{
  "money": 100,
  "currencyType": "USD",
  "depositName": "BYN360"
}
###

GET localhost:8080/depositDetail/admin/findAll/3
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

PUT localhost:8080/depositDetail/pickUp
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

GET localhost:8080/depositDetail/admin/findAllByStatus/OPEN
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

POST localhost:8080/depositDetail/admin/findAllBetweenDate
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

{
  "firstDate": "31-12-2015",
  "secondDate": "31-12-2024"
}
###

DELETE localhost:8080/depositDetail/admin/deleteAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

PUT localhost:8080/depositDetail/admin/refreshAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###