POST localhost:8080/transfer
Content-Type: application/json
token: lhookyf1275652500

{
  "currencyType": "USD",
  "targetWalletValue": "EUR222222222",
  "moneySend": 100
}
###

GET localhost:8080/transfer/getExchangeRates
Content-Type: application/json
token: test
###

POST localhost:8080/transfer//getAll/filterByDate
Content-Type: application/json
token: test

{
  "firstDate": "31-12-2018",
  "secondDate": "31-12-2025"
}
###

GET localhost:8080/transfer/getExchangeRates
Content-Type: application/json
token: test
###

GET localhost:8080/transfer/getAll
Content-Type: application/json
token: test
###

DELETE localhost:8080/transfer/deleteById/3
Content-Type: application/json
token: test
###

DELETE localhost:8080/transfer/deleteAllByDate
Content-Type: application/json
token: test

{
  "firstDate": "31-12-2010",
  "secondDate": "31-12-2015"
}
###