POST localhost:8080/transfer
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

{
  "currencyType": "USD",
  "targetWalletValue": "BYN666666666666",
  "moneySend": 100
}
###

GET localhost:8080/transfer/findAllExchangeRates
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

POST localhost:8080/transfer/admin/findAllBetweenDate
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

{
  "firstDate": "31-12-2018",
  "secondDate": "31-12-2025"
}
###

GET localhost:8080/transfer/admin/findAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

DELETE localhost:8080/transfer/admin/deleteById/1
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

DELETE localhost:8080/transfer/admin/deleteAllBetweenDate
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo

{
  "firstDate": "31-12-2010",
  "secondDate": "31-12-2015"
}
###