POST localhost:8080/user/register
Content-Type: application/json

{
  "email": "examplee@email.com",
  "password": "password",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "MP123456789e",
  "birthday": "11-03-1993",
  "address": {
    "city": "Minsk",
    "street": "Nemiga",
    "house": "12a"
  }
}

###

POST localhost:8080/user/authenticate
Content-Type: application/json

{
  "email": "something@gmail.com",
  "password": "password"
}

###

GET localhost:8080/user/admin/findByEmail/example@email.com
Content-Type: application/json
Authorization: Bearer_yJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

GET localhost:8080/user/admin/findById/3
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

PUT localhost:8080/user/admin/update
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTM0ODAxOSwiZXhwIjoxNTg5MzQ5ODE5fQ.9LfbOhD2tSCMC7liL3CR1-WS30LO3JKSIpox6ZSB7oc

{
  "id": 3,
  "email": "example@email.com",
  "password": "password33",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "edit",
  "birthday": "11-03-1990",
  "address": {
    "city": "Moscow",
    "street": "Voronyma",
    "house": "13a"
  }
}

###

DELETE localhost:8080/user/admin/deleteById/4
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlMkBlbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTU4OTI4NjgzNCwiZXhwIjoxNTg5Mjg4NjM0fQ.WvpJELv4RShpryTk_kgvXjftTxalAekurrf7DxxIjpI
###

GET localhost:8080/user/admin/findAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

PUT localhost:8080/user/admin/establishAdminRole/3
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTE4MzM5MywiZXhwIjoxNTg5MTg0NTkzfQ.S761mxdtoaE4jV4xW9k-kjDiP7tRfxTMLrt4zYy2mqg

###

GET localhost:8080/user/admin/findByWalletValue/USD111111111
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###

PUT localhost:8080/user/admin/changeStatus/3/ACTIVE
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzb21ldGhpbmdAZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iLCJVU0VSIl0sImlhdCI6MTU4OTI4MTExNywiZXhwIjoxNTg5MjgyOTE3fQ.kwheD91m9ifM0EJlWy52P8wCzehYv7Fxc2-XWeRIXeo
###