POST localhost:8080/user/registration
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "MP123456789",
  "birthday": "11-03-1993",
  "address": {
    "city": "Minsk",
    "street": "Nemiga",
    "house": "12a"
  }
}

###

POST localhost:8080/user/authentication
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password"
}

###

GET localhost:8080/user/admin/findByEmail/example@email.com
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQGVtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNTg5MDQ1MTc4LCJleHAiOjE1ODkwNDYzNzh9.NOBukmrjICFkTbB5htHXTrjMJNLp9IRCXAxhv0jZBlc
###

GET localhost:8080/user/admin/findById/2
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlMUBlbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTU4OTA0MzY4NywiZXhwIjoxNTg5MDQ0ODg3fQ.6aW3_jeR9ze_Cl3i83Q5_vQxxs6n07xIdYjRZgBi0zs
###

PUT localhost:8080/user/admin/update
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQGVtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNTg5MDQ1OTYyLCJleHAiOjE1ODkwNDcxNjJ9.z4sspoVmHYSAhVnbMManVoPhyQ0-1iDMHJO1_H7qUr8

{
  "id": 1,
  "email": "edit@email.com",
  "password": "password33",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "edit",
  "birthday": "11-03-1990",
  "address": {
    "city": "Moscow",
    "street": "Nemiga",
    "house": "12a"
  }
}

###

DELETE localhost:8080/user/admin/delete/3
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQGVtYWlsLmNvbSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE1ODkwMzk4NzYsImV4cCI6MTU4OTA0MTA3Nn0.M4vzIe0EM35DWtnXlCnyoSFrz7rQfVOEF5YKX1yIk5I
###

GET localhost:8080/user/admin/findAll
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQGVtYWlsLmNvbSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE1ODkwMzk4NzYsImV4cCI6MTU4OTA0MTA3Nn0.M4vzIe0EM35DWtnXlCnyoSFrz7rQfVOEF5YKX1yIk5I
###

PUT localhost:8080/user/admin/establishAdminRole/2
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQGVtYWlsLmNvbSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE1ODkwMzk4NzYsImV4cCI6MTU4OTA0MTA3Nn0.M4vzIe0EM35DWtnXlCnyoSFrz7rQfVOEF5YKX1yIk5I

###

GET localhost:8080/user/admin/findByWalletValue/USD111111111
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlMUBlbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTU4OTA0MzY4NywiZXhwIjoxNTg5MDQ0ODg3fQ.6aW3_jeR9ze_Cl3i83Q5_vQxxs6n07xIdYjRZgBi0zs
###

PUT localhost:8080/user/admin/changeStatus/2/BLOCKED
Content-Type: application/json
Authorization: Bearer_eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQGVtYWlsLmNvbSIsInJvbGVzIjpbIkFETUlOIiwiVVNFUiJdLCJpYXQiOjE1ODkwMzk4NzYsImV4cCI6MTU4OTA0MTA3Nn0.M4vzIe0EM35DWtnXlCnyoSFrz7rQfVOEF5YKX1yIk5I
###