GET localhost:8080/wallet/create/USD
Content-Type: application/json
token: lhookyf1275652500

###

GET localhost:8080/wallet/getAll
Content-Type: application/json
token: lhookyf1275652500

###

DELETE localhost:8080/wallet/delete/USD
Content-Type: application/json
token: lhookyf1275652500

###

PUT localhost:8080/wallet/clear/USD
Content-Type: application/json
token: lhookyf1275652500

###

POST localhost:8080/wallet/rechargeBalance
Content-Type: application/json
token: lhookyf1275652500

{
  "money": 1000,
  "type": "USD"
}

###