GET localhost:8080/wallet/create/RUB
Content-Type: application/json
token: test

###

GET localhost:8080/wallet/getAll
Content-Type: application/json
token: test

###

DELETE localhost:8080/wallet/delete/USD
Content-Type: application/json
token: test

###

PUT localhost:8080/wallet/clear/USD
Content-Type: application/json
token: test

###

POST localhost:8080/wallet/rechargeBalance
Content-Type: application/json
token: test

{
  "money": 10000,
  "type": "RUB"
}

###