POST localhost:8080/user/registration
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "MP123456789",
  "birthday": "11-03-1993",
  "address": {
    "city": "Minsk",
    "street": "Nemiga",
    "house": "12a"
  }
}

###