POST localhost:8080/transfer
Content-Type: application/json
token: qhjhlvw1018987866

{
  "currencyType": "USD",
  "targetWalletValue": "USD809654392",
  "moneySend": 100
}
###

GET localhost:8080/transfer/getExchangeRates
Content-Type: application/json
token: qhjhlvw1018987866
###