POST localhost:8080/credit/create
Content-Type: application/json
token: test

{
  "name": "USD720",
  "currencyType": "USD",
  "period": 720,
  "rate": 9
}

###

GET localhost:8080/credit/getAllAvailable
Content-Type: application/json
token: test

###

GET localhost:8080/credit/getAll
Content-Type: application/json
token: test

###

GET localhost:8080/credit/findById/1
Content-Type: application/json
token: test

###

DELETE localhost:8080/deposit/delete/1
Content-Type: application/json
token: test

###

DELETE localhost:8080/deposit/deleteAll
Content-Type: application/json
token: test

###