POST localhost:8080/user/registration
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "MP123456789",
  "birthday": "11-03-1993",
  "address": {
    "city": "Minsk",
    "street": "Nemiga",
    "house": "12a"
  }
}

###

POST localhost:8080/user/authorization
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password"
}

###

GET localhost:8080/user/logout
Content-Type: application/json
token: test

###

GET localhost:8080/user/findById/1
Content-Type: application/json
token: test
###

PUT localhost:8080/user/update
Content-Type: application/json
token: test

{
  "id": 5,
  "email": "edit@email.com",
  "password": "password",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "edit",
  "birthday": "11-03-1990",
  "address": {
    "city": "Moscow",
    "street": "Nemiga",
    "house": "12a"
  }
}

###

DELETE localhost:8080/user/delete/1
Content-Type: application/json
token: test
###

GET localhost:8080/user/getAll
Content-Type: application/json
token: test
###

PUT localhost:8080/user/getAdminRole/3
Content-Type: application/json
token: test
###

GET localhost:8080/user/findByWalletValue/USD111111111
Content-Type: application/json
token: test
###

PUT localhost:8080/user/changeStatus/4/BLOCKED
Content-Type: application/json
token: test
###