POST localhost:8080/deposit/create
Content-Type: application/json
token: pkutzqu2096202243

{
  "name": "BYN240",
  "currencyType": "USD",
  "period": 240,
  "rate": 7.1,
  "capitalization": null
}

###

GET localhost:8080/deposit/getAllAvailable
Content-Type: application/json
token: pkutzqu2096202243
###

GET localhost:8080/deposit/getAll
Content-Type: application/json
token: pkutzqu2096202243
###

GET localhost:8080/deposit/findById/1
Content-Type: application/json
token: pkutzqu2096202243
###

PUT localhost:8080/deposit/update
Content-Type: application/json
token: pkutzqu2096202243

{
  "id": 1,
  "name": "updated",
  "currencyType": "BYN",
  "period": 240,
  "rate": 3.6,
  "status": "DELETED",
  "capitalization": true
}

###





