POST localhost:8080/user/registration
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "MP123456789",
  "birthday": "11-03-1993",
  "address": {
    "city": "Minsk",
    "street": "Nemiga",
    "house": "12a"
  }
}

###

POST localhost:8080/user/authorization
Content-Type: application/json

{
  "email": "example@email.com",
  "password": "password"
}

###

GET localhost:8080/user/logout
Content-Type: application/json
token: benkilq-1627313068

###

GET localhost:8080/user/findById/1
Content-Type: application/json
token: zxdpmnm-631285338
###

PUT localhost:8080/user/update
Content-Type: application/json
token: zxdpmnm-631285338

{
  "id": 1,
  "email": "edit@email.com",
  "password": "password",
  "firstName": "first name",
  "lastName": "last name",
  "passport": "edit",
  "birthday": "11-03-1990",
  "address": {
    "city": "Moscow",
    "street": "Nemiga",
    "house": "12a"
  }
}

###

DELETE localhost:8080/user/delete/3
Content-Type: application/json
token: idbjsxi319461464
###

GET localhost:8080/user/getAll
Content-Type: application/json
token: zxdpmnm-631285338
###

PUT localhost:8080/user/getAdminRole/2
Content-Type: application/json
token: snijhrj-1236018832
###