GET localhost:8080/wallet/create/USD
Content-Type: application/json
token: lycxqdx-1168056860

###

GET localhost:8080/wallet/getAll
Content-Type: application/json
token: luqotof55656255

###

DELETE localhost:8080/wallet/delete/USD
Content-Type: application/json
token: mltjejd1279580875

###

POST localhost:8080/wallet/rechargeBalance
Content-Type: application/json
token: lycxqdx-1168056860

{
  "money": 1000,
  "type": "USD"
}

###